import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import {
  BadgeCheck,
  Calendar,
  Download,
  FileCheck2,
  FileInput,
  FileText,
  Fingerprint,
  Hash,
  PenLine,
  RotateCcw,
  ShieldCheck,
  Upload,
} from "lucide-react";
import type { LucideIcon } from "lucide-react";
import { PDFDocument, rgb, StandardFonts } from "pdf-lib";
import * as pdfjsLib from "pdfjs-dist";
import pdfWorker from "pdfjs-dist/build/pdf.worker.mjs?url";

pdfjsLib.GlobalWorkerOptions.workerSrc = pdfWorker;

type SignatureMode = "draw" | "type";

type Placement = {
  x: number;
  y: number;
  width: number;
  height: number;
};

type PageMetrics = {
  pdfWidth: number;
  pdfHeight: number;
  previewWidth: number;
  previewHeight: number;
};

type Certificate = {
  app: string;
  version: string;
  documentName: string;
  signerName: string;
  signedAt: string;
  pageNumber: number;
  originalSha256: string;
  signedSha256: string;
  signatureMode: SignatureMode;
  placement: Placement;
};

const initialPlacement: Placement = {
  x: 0.16,
  y: 0.72,
  width: 0.34,
  height: 0.095,
};

const today = new Intl.DateTimeFormat("en-US", {
  month: "short",
  day: "2-digit",
  year: "numeric",
}).format(new Date());

function clamp(value: number, min: number, max: number) {
  return Math.min(Math.max(value, min), max);
}

function bytesToHex(buffer: ArrayBuffer) {
  return Array.from(new Uint8Array(buffer))
    .map((byte) => byte.toString(16).padStart(2, "0"))
    .join("");
}

async function sha256Hex(bytes: Uint8Array) {
  const source = new ArrayBuffer(bytes.byteLength);
  new Uint8Array(source).set(bytes);
  const digest = await crypto.subtle.digest("SHA-256", source);
  return bytesToHex(digest);
}

function shortHash(hash?: string) {
  if (!hash) return "pending";
  return `${hash.slice(0, 12)}...${hash.slice(-8)}`;
}

function downloadBlob(blob: Blob, filename: string) {
  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  link.remove();
  URL.revokeObjectURL(url);
}

function safeFilename(filename: string, suffix: string) {
  const base = filename.replace(/\.pdf$/i, "").replace(/[^a-z0-9-_]+/gi, "-");
  return `${base || "document"}-${suffix}`;
}

async function createSamplePdf() {
  const pdfDoc = await PDFDocument.create();
  const page = pdfDoc.addPage([612, 792]);
  const heading = await pdfDoc.embedFont(StandardFonts.HelveticaBold);
  const body = await pdfDoc.embedFont(StandardFonts.Helvetica);
  const italic = await pdfDoc.embedFont(StandardFonts.TimesRomanItalic);

  page.drawText("Volunteer Activity Waiver", {
    x: 58,
    y: 718,
    size: 22,
    font: heading,
    color: rgb(0.08, 0.1, 0.12),
  });
  page.drawText("Sample document for local signing workflow validation", {
    x: 58,
    y: 690,
    size: 10,
    font: body,
    color: rgb(0.36, 0.4, 0.44),
  });

  const copy = [
    "I understand that participation in this volunteer activity may involve ordinary risks",
    "including travel, physical movement, and contact with public spaces. I certify that I",
    "am voluntarily participating and that the information I provide is accurate.",
    "",
    "This sample is generated locally for testing the signing flow. It is not legal advice",
    "and should be replaced with the actual document before use.",
  ];

  copy.forEach((line, index) => {
    page.drawText(line, {
      x: 58,
      y: 636 - index * 20,
      size: 11,
      font: body,
      color: rgb(0.14, 0.16, 0.18),
    });
  });

  page.drawRectangle({
    x: 52,
    y: 120,
    width: 508,
    height: 112,
    borderWidth: 1,
    borderColor: rgb(0.78, 0.81, 0.84),
  });
  page.drawText("Signature", {
    x: 68,
    y: 201,
    size: 9,
    font: body,
    color: rgb(0.36, 0.4, 0.44),
  });
  page.drawLine({
    start: { x: 68, y: 172 },
    end: { x: 278, y: 172 },
    thickness: 0.8,
    color: rgb(0.56, 0.6, 0.64),
  });
  page.drawText("Date", {
    x: 336,
    y: 201,
    size: 9,
    font: body,
    color: rgb(0.36, 0.4, 0.44),
  });
  page.drawLine({
    start: { x: 336, y: 172 },
    end: { x: 492, y: 172 },
    thickness: 0.8,
    color: rgb(0.56, 0.6, 0.64),
  });
  page.drawText("Generated by Personal Signing Vault", {
    x: 58,
    y: 54,
    size: 9,
    font: italic,
    color: rgb(0.42, 0.45, 0.48),
  });

  return new Uint8Array(await pdfDoc.save());
}

export default function App() {
  const fileInputRef = useRef<HTMLInputElement>(null);
  const previewCanvasRef = useRef<HTMLCanvasElement>(null);
  const previewStageRef = useRef<HTMLDivElement>(null);
  const signatureCanvasRef = useRef<HTMLCanvasElement>(null);
  const dragOffsetRef = useRef({ x: 0, y: 0 });

  const [documentName, setDocumentName] = useState("");
  const [documentBytes, setDocumentBytes] = useState<Uint8Array | null>(null);
  const [originalHash, setOriginalHash] = useState("");
  const [signedHash, setSignedHash] = useState("");
  const [pageMetrics, setPageMetrics] = useState<PageMetrics | null>(null);
  const [placement, setPlacement] = useState(initialPlacement);
  const [signerName, setSignerName] = useState("Thupten Wangpo");
  const [signatureMode, setSignatureMode] = useState<SignatureMode>("draw");
  const [typedSignature, setTypedSignature] = useState("");
  const [drawnSignatureDataUrl, setDrawnSignatureDataUrl] = useState("");
  const [includeDate, setIncludeDate] = useState(true);
  const [hasDrawnSignature, setHasDrawnSignature] = useState(false);
  const [isDrawing, setIsDrawing] = useState(false);
  const [isDragging, setIsDragging] = useState(false);
  const [certificate, setCertificate] = useState<Certificate | null>(null);
  const [statusMessage, setStatusMessage] = useState("Load a PDF to begin.");
  const [errorMessage, setErrorMessage] = useState("");

  const canSign =
    Boolean(documentBytes) &&
    signerName.trim().length > 0 &&
    (signatureMode === "type"
      ? typedSignature.trim().length > 0
      : hasDrawnSignature);

  const signatureLabel =
    signatureMode === "type" ? typedSignature.trim() : signerName.trim();

  const loadPdfBytes = useCallback(async (name: string, bytes: Uint8Array) => {
    setErrorMessage("");
    setDocumentName(name);
    setDocumentBytes(bytes);
    setOriginalHash(await sha256Hex(bytes));
    setSignedHash("");
    setCertificate(null);
    setPlacement(initialPlacement);
    setStatusMessage("PDF loaded. Place your signature and export when ready.");
  }, []);

  useEffect(() => {
    if (!documentBytes || !previewCanvasRef.current) return;

    let cancelled = false;
    const bytes = documentBytes.slice();

    async function renderFirstPage() {
      try {
        const loadingTask = pdfjsLib.getDocument({ data: bytes });
        const pdf = await loadingTask.promise;
        const page = await pdf.getPage(1);
        const viewport = page.getViewport({ scale: 1.35 });
        const canvas = previewCanvasRef.current;
        if (!canvas || cancelled) return;

        const context = canvas.getContext("2d");
        if (!context) return;

        const outputScale = window.devicePixelRatio || 1;
        canvas.width = Math.floor(viewport.width * outputScale);
        canvas.height = Math.floor(viewport.height * outputScale);

        await page.render({
          canvasContext: context,
          viewport,
          transform:
            outputScale !== 1
              ? [outputScale, 0, 0, outputScale, 0, 0]
              : undefined,
        }).promise;

        if (!cancelled) {
          const [x1, y1, x2, y2] = page.view;
          setPageMetrics({
            pdfWidth: x2 - x1,
            pdfHeight: y2 - y1,
            previewWidth: viewport.width,
            previewHeight: viewport.height,
          });
        }
      } catch (error) {
        if (!cancelled) {
          setErrorMessage(
            error instanceof Error ? error.message : "Could not render PDF.",
          );
          setStatusMessage("PDF preview failed.");
        }
      }
    }

    renderFirstPage();

    return () => {
      cancelled = true;
    };
  }, [documentBytes]);

  const loadSample = async () => {
    const sample = await createSamplePdf();
    await loadPdfBytes("sample-volunteer-waiver.pdf", sample);
  };

  const handleFileChange = async (
    event: React.ChangeEvent<HTMLInputElement>,
  ) => {
    const file = event.target.files?.[0];
    if (!file) return;
    if (file.type !== "application/pdf" && !file.name.endsWith(".pdf")) {
      setErrorMessage("Choose a PDF file.");
      return;
    }
    await loadPdfBytes(file.name, new Uint8Array(await file.arrayBuffer()));
  };

  const getSignaturePoint = (event: React.PointerEvent<HTMLCanvasElement>) => {
    const canvas = signatureCanvasRef.current;
    if (!canvas) return null;
    const rect = canvas.getBoundingClientRect();
    return {
      x: ((event.clientX - rect.left) / rect.width) * canvas.width,
      y: ((event.clientY - rect.top) / rect.height) * canvas.height,
    };
  };

  const startSignature = (event: React.PointerEvent<HTMLCanvasElement>) => {
    const point = getSignaturePoint(event);
    const canvas = signatureCanvasRef.current;
    const context = canvas?.getContext("2d");
    if (!point || !canvas || !context) return;

    canvas.setPointerCapture(event.pointerId);
    context.strokeStyle = "#101820";
    context.lineWidth = 4.5;
    context.lineCap = "round";
    context.lineJoin = "round";
    context.beginPath();
    context.moveTo(point.x, point.y);
    setIsDrawing(true);
    setHasDrawnSignature(true);
    setSignedHash("");
    setCertificate(null);
  };

  const drawSignature = (event: React.PointerEvent<HTMLCanvasElement>) => {
    if (!isDrawing) return;
    const point = getSignaturePoint(event);
    const context = signatureCanvasRef.current?.getContext("2d");
    if (!point || !context) return;
    context.lineTo(point.x, point.y);
    context.stroke();
  };

  const stopSignature = (event: React.PointerEvent<HTMLCanvasElement>) => {
    if (signatureCanvasRef.current?.hasPointerCapture(event.pointerId)) {
      signatureCanvasRef.current.releasePointerCapture(event.pointerId);
    }
    if (hasDrawnSignature && signatureCanvasRef.current) {
      setDrawnSignatureDataUrl(signatureCanvasRef.current.toDataURL("image/png"));
    }
    setIsDrawing(false);
  };

  const clearSignature = () => {
    const canvas = signatureCanvasRef.current;
    const context = canvas?.getContext("2d");
    if (canvas && context) {
      context.clearRect(0, 0, canvas.width, canvas.height);
    }
    setHasDrawnSignature(false);
    setDrawnSignatureDataUrl("");
    setSignedHash("");
    setCertificate(null);
  };

  const startPlacementDrag = (event: React.PointerEvent<HTMLDivElement>) => {
    if (!previewStageRef.current) return;
    const rect = previewStageRef.current.getBoundingClientRect();
    const currentX = placement.x * rect.width;
    const currentY = placement.y * rect.height;
    dragOffsetRef.current = {
      x: event.clientX - rect.left - currentX,
      y: event.clientY - rect.top - currentY,
    };
    event.currentTarget.setPointerCapture(event.pointerId);
    setIsDragging(true);
  };

  const updatePlacementFromPointer = (event: React.PointerEvent) => {
    if (!isDragging || !previewStageRef.current) return;
    const rect = previewStageRef.current.getBoundingClientRect();
    const nextX =
      (event.clientX - rect.left - dragOffsetRef.current.x) / rect.width;
    const nextY =
      (event.clientY - rect.top - dragOffsetRef.current.y) / rect.height;

    setPlacement((current) => ({
      ...current,
      x: clamp(nextX, 0.02, 1 - current.width - 0.02),
      y: clamp(nextY, 0.02, 1 - current.height - 0.02),
    }));
    setSignedHash("");
    setCertificate(null);
  };

  const stopPlacementDrag = (event: React.PointerEvent<HTMLDivElement>) => {
    if (event.currentTarget.hasPointerCapture(event.pointerId)) {
      event.currentTarget.releasePointerCapture(event.pointerId);
    }
    setIsDragging(false);
  };

  const exportSignedPdf = async () => {
    if (!documentBytes || !pageMetrics || !canSign) return;

    setErrorMessage("");
    setStatusMessage("Signing PDF locally...");

    try {
      const pdfDoc = await PDFDocument.load(documentBytes);
      const page = pdfDoc.getPages()[0];
      const { width: pdfWidth, height: pdfHeight } = page.getSize();
      const x = placement.x * pdfWidth;
      const boxWidth = placement.width * pdfWidth;
      const boxHeight = placement.height * pdfHeight;
      const y = pdfHeight - placement.y * pdfHeight - boxHeight;
      const nameY = Math.max(26, y - 14);

      const helvetica = await pdfDoc.embedFont(StandardFonts.Helvetica);
      const helveticaBold = await pdfDoc.embedFont(StandardFonts.HelveticaBold);
      const italic = await pdfDoc.embedFont(StandardFonts.TimesRomanItalic);

      if (signatureMode === "draw") {
        const dataUrl = signatureCanvasRef.current?.toDataURL("image/png");
        if (!dataUrl) throw new Error("No drawn signature found.");
        const pngBytes = await fetch(dataUrl).then((response) =>
          response.arrayBuffer(),
        );
        const signatureImage = await pdfDoc.embedPng(pngBytes);
        page.drawImage(signatureImage, {
          x,
          y,
          width: boxWidth,
          height: boxHeight,
        });
      } else {
        page.drawText(typedSignature.trim(), {
          x,
          y: y + boxHeight * 0.26,
          size: Math.min(34, boxHeight * 0.52),
          font: italic,
          color: rgb(0.04, 0.09, 0.11),
        });
      }

      page.drawText(signerName.trim(), {
        x,
        y: nameY,
        size: 8.5,
        font: helveticaBold,
        color: rgb(0.08, 0.12, 0.14),
      });

      if (includeDate) {
        page.drawText(today, {
          x: x + boxWidth * 0.58,
          y: nameY,
          size: 8.5,
          font: helvetica,
          color: rgb(0.12, 0.16, 0.18),
        });
      }

      page.drawText("Signed locally with Personal Signing Vault", {
        x,
        y: Math.max(14, nameY - 12),
        size: 6.8,
        font: helvetica,
        color: rgb(0.38, 0.42, 0.46),
      });

      const signedBytes = new Uint8Array(await pdfDoc.save());
      const nextSignedHash = await sha256Hex(signedBytes);
      const signedAt = new Date().toISOString();
      const nextCertificate: Certificate = {
        app: "Personal Signing Vault",
        version: "0.1.0",
        documentName,
        signerName: signerName.trim(),
        signedAt,
        pageNumber: 1,
        originalSha256: originalHash,
        signedSha256: nextSignedHash,
        signatureMode,
        placement,
      };

      setSignedHash(nextSignedHash);
      setCertificate(nextCertificate);
      setStatusMessage("Signed PDF and evidence certificate are ready.");

      downloadBlob(
        new Blob([signedBytes], { type: "application/pdf" }),
        `${safeFilename(documentName, "signed")}.pdf`,
      );
    } catch (error) {
      setErrorMessage(
        error instanceof Error ? error.message : "Could not sign PDF.",
      );
      setStatusMessage("Signing failed.");
    }
  };

  const downloadCertificate = () => {
    if (!certificate) return;
    downloadBlob(
      new Blob([JSON.stringify(certificate, null, 2)], {
        type: "application/json",
      }),
      `${safeFilename(documentName, "certificate")}.json`,
    );
  };

  const completionLabel = useMemo(() => {
    if (!documentBytes) return "Import";
    if (!canSign) return "Place";
    if (!signedHash) return "Evidence";
    return "Complete";
  }, [canSign, documentBytes, signedHash]);

  const workflowSteps: Array<{
    label: string;
    Icon: LucideIcon;
    done: boolean;
  }> = [
    { label: "Import", Icon: FileInput, done: Boolean(documentBytes) },
    { label: "Place", Icon: PenLine, done: canSign },
    { label: "Evidence", Icon: FileCheck2, done: Boolean(signedHash) },
  ];

  return (
    <main className="app-shell">
      <header className="topbar">
        <div className="brand-block">
          <div className="brand-mark" aria-hidden="true">
            <ShieldCheck size={20} />
          </div>
          <div>
            <h1>Personal Signing Vault</h1>
            <p>{documentName || "No document loaded"}</p>
          </div>
        </div>

        <div className="topbar-actions">
          <span className={`status-pill ${signedHash ? "ready" : ""}`}>
            <BadgeCheck size={15} />
            {completionLabel}
          </span>
          <button
            className="primary-button"
            disabled={!canSign}
            onClick={exportSignedPdf}
          >
            <Download size={17} />
            Export signed PDF
          </button>
        </div>
      </header>

      <section className="workspace">
        <aside className="workflow-rail" aria-label="Signing workflow">
          {workflowSteps.map(({ label, Icon, done }) => (
            <div
              className={`rail-step ${done ? "done" : ""}`}
              key={label}
            >
              <div className="rail-icon">
                <Icon size={18} />
              </div>
              <span>{label}</span>
            </div>
          ))}
        </aside>

        <section className="document-panel" aria-label="Document workspace">
          <div className="document-toolbar">
            <div>
              <span className="section-label">Document preview</span>
              <strong>{documentName || "Waiting for PDF"}</strong>
            </div>
            <div className="toolbar-actions">
              <input
                ref={fileInputRef}
                className="sr-only"
                type="file"
                accept="application/pdf"
                onChange={handleFileChange}
              />
              <button
                className="secondary-button"
                onClick={() => fileInputRef.current?.click()}
              >
                <Upload size={16} />
                Upload PDF
              </button>
              <button className="secondary-button" onClick={loadSample}>
                <FileText size={16} />
                Load sample
              </button>
            </div>
          </div>

          <div className="preview-shell">
            {documentBytes ? (
              <div
                ref={previewStageRef}
                className="page-stage"
                onPointerMove={updatePlacementFromPointer}
                style={
                  pageMetrics
                    ? {
                        aspectRatio: `${pageMetrics.previewWidth} / ${pageMetrics.previewHeight}`,
                      }
                    : undefined
                }
              >
                <canvas ref={previewCanvasRef} className="pdf-canvas" />
                <div
                  className={`signature-box ${isDragging ? "dragging" : ""}`}
                  role="button"
                  tabIndex={0}
                  aria-label="Draggable signature placement"
                  onPointerDown={startPlacementDrag}
                  onPointerUp={stopPlacementDrag}
                  onPointerCancel={stopPlacementDrag}
                  style={{
                    left: `${placement.x * 100}%`,
                    top: `${placement.y * 100}%`,
                    width: `${placement.width * 100}%`,
                    height: `${placement.height * 100}%`,
                  }}
                >
                  {signatureMode === "draw" && drawnSignatureDataUrl ? (
                    <img
                      className="signature-image-preview"
                      src={drawnSignatureDataUrl}
                      alt="Drawn signature preview"
                    />
                  ) : (
                    <span className="signature-preview">{signatureLabel}</span>
                  )}
                  <small>{includeDate ? today : "date off"}</small>
                </div>
              </div>
            ) : (
              <div className="empty-document">
                <FileText size={42} />
                <h2>Start with a PDF</h2>
                <p>
                  Upload a waiver or load the sample document to test the local
                  signing flow.
                </p>
                <div className="empty-actions">
                  <button
                    className="primary-button"
                    onClick={() => fileInputRef.current?.click()}
                  >
                    <Upload size={17} />
                    Upload PDF
                  </button>
                  <button className="secondary-button" onClick={loadSample}>
                    <FileText size={16} />
                    Load sample
                  </button>
                </div>
              </div>
            )}
          </div>
        </section>

        <aside className="inspector" aria-label="Signing controls">
          <section className="inspector-section">
            <div className="section-heading">
              <Fingerprint size={18} />
              <h2>Signer</h2>
            </div>
            <label className="field-label" htmlFor="signer-name">
              Legal name
            </label>
            <input
              id="signer-name"
              value={signerName}
              onChange={(event) => {
                setSignerName(event.target.value);
                setSignedHash("");
                setCertificate(null);
              }}
              placeholder="Your name"
            />
          </section>

          <section className="inspector-section">
            <div className="section-heading">
              <PenLine size={18} />
              <h2>Signature</h2>
            </div>
            <div className="segmented-control" aria-label="Signature mode">
              <button
                className={signatureMode === "draw" ? "active" : ""}
                onClick={() => setSignatureMode("draw")}
              >
                Draw
              </button>
              <button
                className={signatureMode === "type" ? "active" : ""}
                onClick={() => setSignatureMode("type")}
              >
                Type
              </button>
            </div>

            {signatureMode === "draw" ? (
              <div className="signature-pad-wrap">
                <canvas
                  ref={signatureCanvasRef}
                  className="signature-pad"
                  width={720}
                  height={220}
                  onPointerDown={startSignature}
                  onPointerMove={drawSignature}
                  onPointerUp={stopSignature}
                  onPointerCancel={stopSignature}
                />
                <button className="icon-button" onClick={clearSignature}>
                  <RotateCcw size={15} />
                  Clear
                </button>
              </div>
            ) : (
              <label className="typed-signature">
                <span>Typed signature</span>
                <input
                  value={typedSignature}
                  onChange={(event) => {
                    setTypedSignature(event.target.value);
                    setSignedHash("");
                    setCertificate(null);
                  }}
                  placeholder="Type your signature"
                />
              </label>
            )}

            <label className="toggle-row">
              <input
                type="checkbox"
                checked={includeDate}
                onChange={(event) => {
                  setIncludeDate(event.target.checked);
                  setSignedHash("");
                  setCertificate(null);
                }}
              />
              <span>
                <Calendar size={15} />
                Include today&apos;s date
              </span>
            </label>
          </section>

          <section className="inspector-section evidence">
            <div className="section-heading">
              <Hash size={18} />
              <h2>Evidence bundle</h2>
            </div>
            <dl>
              <div>
                <dt>Original SHA-256</dt>
                <dd>{shortHash(originalHash)}</dd>
              </div>
              <div>
                <dt>Signed SHA-256</dt>
                <dd>{shortHash(signedHash)}</dd>
              </div>
              <div>
                <dt>Timestamp</dt>
                <dd>{certificate?.signedAt ?? "created on export"}</dd>
              </div>
            </dl>
            <button
              className="secondary-button full"
              disabled={!certificate}
              onClick={downloadCertificate}
            >
              <Download size={16} />
              Download certificate JSON
            </button>
          </section>
        </aside>
      </section>

      <footer className="statusbar">
        <span>{statusMessage}</span>
        {errorMessage ? <strong>{errorMessage}</strong> : null}
        <span className="statusbar-note">
          Local-only prototype. No upload, no identity proofing.
        </span>
      </footer>
    </main>
  );
}
